# Generated by Django 6.1.1 on 2026-09-14 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='The core study material for this guide.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_guides', to='accounts.teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_guides', to='accounts.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('reading', 'Reading'), ('practice', 'Practice'), ('video', 'Video'), ('discussion', 'Discussion')], default='reading', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('study_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='study.studyguide')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='accounts.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='accounts.student')),
                ('study_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='study.studyguide')),
            ],
            options={
                'verbose_name_plural': 'Student progress records',
                'ordering': ['-assigned_at'],
                'unique_together': {('student', 'study_guide')},
            },
        ),
    ]
