# Generated by Django 6.1.1 on 2026-09-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('school_admin', 'School Administrator'), ('parent', 'Parent / Guardian'), ('other', 'Other')], default='student', max_length=20)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Waitlist signup',
                'verbose_name_plural': 'Waitlist signups',
                'ordering': ['-created_at'],
            },
        ),
    ]
